# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20160501_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegrammessage',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='telegrammessage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='telegrammessage',
            name='username',
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
